version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    image: 'nginx:alpine'
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html # This volume will be populated by the app build
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local